class Symbols:
    """Common UI symbols used across the app."""
    arrow = "➤"
    check = "✔"
    cross = "✖"
    warning = "⚠"
    info = "ℹ"
    right_arrow = "→"
    bullet = "•"
    ellipsis = "…"
    box = "▣"
    circle = "◉"
    spinner_down = "⟳"
    spinner_up = "↻"
    attachment = "📎"
